### ISSUE TITLE
Port from blockstack.js

### ISSUE THREAD

**Issue by vsund** [ntzwrk/blockstack.ts#3]
This issue documents my steps for porting over from [`blockstack.js`](https://github.com/blockstack/blockstack.js). I forked at [commit `286df82`](https://github.com/blockstack/blockstack.js/tree/286df82401c5be8d89e352054e2192e0f600ea98) and will backport coming changes from upstream `blockstack.js`.

I began with copying over the `src/` directory over to here and then gradually fixing the problems `tsc`complains about.

I try to document here everything that might be either relevant for fixing it upstream or needs some clarification. For all actions I took please review the commits starting from 11e1c78 (these may contain also minor things that might be relevant for upstream).

### Steps
* [x] `yarn build` (with `strict=false`)
* [x] `yarn build` (with `strict=true`) (except the points below)
* [x] `yarn lint`
* [x] Restructuring
* [x] `yarn test`
* [ ] Code review (and refactoring)
  * [x] Improve file structure
  * [ ] Revisit class attribute visibility
  * [x] Revisit exports
  * [ ] Document all code
  * [ ] Revisit provided developer interfaces

### Issues
* [x] Clarify dependencies: #4, possible solution in 7587875bd40e7cba0e0b18e50713a7a87097cd93
* [ ] Types for `custom-protocol-detection-blockstack`: #5, possible solution in [my fork](https://github.com/vsund/custom-protocol-detection/tree/feature/add-typescript-declarations)
* [ ] Types for `jsontokens`: possible solution in https://github.com/blockstack/jsontokens-js/pull/20
* [ ] Types for `zone-file`: possible solution in https://github.com/blockstack/zone-file-js/pull/4
* [x] Types for `bn.js`: https://github.com/indutny/bn.js/pull/180
* [ ] Clarify whether writes to window.location.href are correct #6, possible solution in 4ee243a030a46865a9b9e8e55eeb43f6cd317aab
* [x] Clarify whether `getGracePeriod()` needs a parameter or not: #7, possible solution in 329c6a601bf67380eaa5ed6b9122e075802f33e6
* [ ] Where does the parameter for `verifiedAccounts()` should come from?: #8
* [x] Clarify return type of `decryptPrivateKey()`: #9
* [x] Can `encryptECIES()` take a Buffer as input? #10, possible solution in ae6bc6015fe2e3c5edbb414badc2f74c97e2b7b2
* [x] Is the `form-data` dependency needed?: #13
* [x] `@types/bitcoinjs-lib`: `ECPair` should expose `compressed`: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24453
* [x] `@types/bigi`: Wrong return type for `valueOf`: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24346

### Flaws
* `AuthMessage` should be exported: 1a3810d1cc9b56aa403780adefaec21a0b7181af
* `ErrorType` should be exported and wrong parameter name: 3116488faf12b10ee9a200c060e1de0ba736511f
* `UTXO` should be exported: 35dd81d033af399c72aa80290c57d65b8dec4b1c
* Use library-native `UTXO` type: 3c85b561983af26036a31a5f33ef663eb2793b3d

### Things needed for a strict build
* [ ] Types for [`elliptic`](https://github.com/indutny/elliptic)
* [ ] Types for [`ripemd160`](https://github.com/crypto-browserify/ripemd160)

---
Note: I'll update this issue consistently with links to other ones etc, while porting over. The solutions behind the issue numbers are most likely opinionated (but need them to go forward with the port).
Also please don't be frightened by all these imperatives, I just write all my git related messages as imperative :D

Edit: Just decided to make a new list of flaws for things that don't need a discussion (in my opinion).

Edit: These **may contain false-positives** because of style variations or dependency upgrades.

cc @kantai @larrysalibra
